# Generated by Django 5.2.7 on 2025-10-30 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_look", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PecaRoupa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_peca", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=50)),
                ("cor", models.CharField(max_length=50)),
                ("tamanho", models.CharField(blank=True, max_length=20)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="pecas/"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LookPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "look",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="closet.look"
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="closet.pecaroupa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="look",
            name="pecas",
            field=models.ManyToManyField(
                through="closet.LookPeca", to="closet.pecaroupa"
            ),
        ),
        migrations.CreateModel(
            name="Gostar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_gosto", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "look",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="closet.look"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "look")},
            },
        ),
    ]
