# Generated by Django 5.2.8 on 2025-11-28 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="look",
            name="foto_principal",
            field=models.ImageField(blank=True, null=True, upload_to="looks/"),
        ),
        migrations.AddField(
            model_name="lookpeca",
            name="data_adicao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="look",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="look",
            name="pecas",
            field=models.ManyToManyField(
                related_name="looks", through="closet.LookPeca", to="closet.pecaroupa"
            ),
        ),
    ]
